version: '3.9'

services:

  kong:
    extra_hosts:
      - "${API_DOMAIN}:${HOST}"
      - "${MINIO_DOMAIN}:${HOST}"
      - "${MINIO_CONSOLE_DOMAIN}:${HOST}"
    build:
      context: .
      dockerfile: .dev/kong/Dockerfile
    ports:
      - ${HTTP_PORT-80}:8000
      - ${HTTPS_PORT-443}:8443
    environment:
      KONG_DATABASE: 'off'
    volumes:
      - .dev/kong/kong.yml:/kong.yml:ro
    env_file:
      - .env


  dotnet.s3.api:
    ports:
      - "80"
    #environment:
      #Serilog__MinimumLevel__Default: Debug
      #Serilog__MinimumLevel__Override__Microsoft: Debug

  s3:
    build:
      context: .
      dockerfile: .dev/minio/Dockerfile
    extra_hosts:
      - "${MINIO_DOMAIN}:${HOST}"
    command: server --console-address ":9001" /data
    volumes:
      - ./.s3:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
